
name: ETL Pipeline

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t etl-pipeline .
      - name: Run ETL
        run: docker run etl-pipeline
